CREATE TABLE INSTRUTORES
(COD_INSTRUTOR NUMBER(03) 
CONTRAINT PRIMARY KEY,
NOME_INSTRUTOR VARCHAR2(30) CONSTRAINT NOT NULL,
TEL_INSTRUTOR VARCHAR2(10),
ADMISSAO DATE DEFAULT SYSDATE);

CREATE TABLE INSTRUTORES
(COD_INSTRUTOR NUMBER(03) PRIMARY KEY,
NOME_INSTRUTOR VARCHAR2(30) NOT NULL,
TEL_INSTRUTOR VARCHAR2(10),
ADMISSAO DATE DEFAULT SYSDATE);

DROP TABLE INSTRUTORES CASCADE CONSTRAINT
